-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e626cd57090d8df0be21e4df0f4e55cc3511d6ab
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
-   repo: git@github.com:Lucas-C/pre-commit-hooks.git
    sha: v1.0.1
    hooks:
    -   id: forbid-tabs
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: 'master'
    hooks:
    -   id: jshint
